package com.swamwithturtles.decrypto.model;

public enum GameStatus {
    WAITING,
    GENERATING,
    BETWEEN_TURNS,
    AWAITING_GUESSWORDS,
    AWAITING_GUESSES_RED_OPPOSITION,
    AWAITING_GUESSES_BLUE_OPPOSITION,
    AWAITING_GUESSES_RED_FRIENDLY,
    AWAITING_GUESSES_BLUE_FRIENDLY,
    END_OF_TURN_TRANSITION,
    AWAITING_ACKNOWLEDGEMENTS,
    END_OF_GAME
}
